2019-01-24T17:21:10|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\eclipse-workspace\laser\laser_hardware.py", line 36, in connect
    self.laser_power.vmax=float(self.power_rating.val)
ValueError: could not convert string to float: 

